// <auto-generated />
namespace CarpoolingCR.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Addedfromandtodistrictstotrip : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addedfromandtodistrictstotrip));
        
        string IMigrationMetadata.Id
        {
            get { return "201908020133172_Added from and to districts to trip"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
