// <auto-generated />
namespace CarpoolingCR.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class createdBlockedAmount : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(createdBlockedAmount));
        
        string IMigrationMetadata.Id
        {
            get { return "201911272343039_created BlockedAmount"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
