// <auto-generated />
namespace CarpoolingCR.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Deletedtripreservationandnotificationcountsfromusersincetheyarenotreallynecessary : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Deletedtripreservationandnotificationcountsfromusersincetheyarenotreallynecessary));
        
        string IMigrationMetadata.Id
        {
            get { return "201910022317227_Deleted trip, reservation and notification counts from user since they are not really necessary"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
