// <auto-generated />
namespace CarpoolingCR.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Changeduseridfrominttostringinrequestnotifications : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Changeduseridfrominttostringinrequestnotifications));
        
        string IMigrationMetadata.Id
        {
            get { return "201909042333469_Changed user id from int to string in request notifications"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
